Update M08_TWAS

diff --git a/script/M08_TWAS b/script/M08_TWAS
--- a/script/M08_TWAS
+++ b/script/M08_TWAS
@@ -1,1 +1,63 @@
-
+#!/bin/bash
+#scpredixcan
+source ~/.bashrc
+conda activate imlatools
+cd "/node1/liuxy/MediCell/pbmc/TWAS/output/TWAS_2/"
+declare -A celltypes=(
+    ["pbmc"]="CD4T CD8T NK B Mono DC"
+#    ["tub"]="PT LOH DCT CDICA CDICB MNP pDC NK NKT CD8T Bcell Th_cell"
+#    ["glom"]="Endo Podo MC NK NKT Th_cell CD8T Bcell MNP"
+)
+declare -A tissue_paths=(
+    ["pbmc_db"]="/node1/liuxy/MediCell/pbmc/TWAS/usefile/db_2/"
+    ["pbmc_cov"]="/node1/liuxy/MediCell/pbmc/TWAS/usefile/cov_6/"
+#    ["glom_db"]="/node1/liuxy/MediCell/pbmc/TWAS/usefile/db_2/"
+#    ["glom_cov"]="/node1/liuxy/MediCell/pbmc/TWAS/usefile/cov_2/"
+)
+disease_name="SLE"
+gwas_files=/node1/liuxy/MediCell/pbmc/TWAS/usefile/bentham_2015_26502338_sle_processed_beta.tsv
+output_base="/node1/liuxy/MediCell/pbmc/TWAS/output/TWAS_2/"
+for gwas_path in "${gwas_files[@]}"; do
+    disease_name=$(basename $(dirname "$gwas_path"))
+    disease_name="SLE"
+    for tissue in "${!celltypes[@]}"; do
+        tissue_output_dir="${output_base}/${tissue}/${disease_name}"
+        mkdir -p "$tissue_output_dir"
+        db_path="${tissue_paths[${tissue}_db]}"
+        cov_path="${tissue_paths[${tissue}_cov]}"
+        
+        for ct_value in ${celltypes[$tissue]}; do
+            output_file="${tissue_output_dir}/${ct_value}.csv"
+            log_file="${tissue_output_dir}/${ct_value}.log"
+            
+            if [[ "$tissue" == "pbmc" ]]; then
+                db_file="${db_path}/${ct_value}_PCs_and_age_gender_models_filtered_signif.db"
+            else
+                db_file="${db_path}/${ct_value}.db"
+            fi
+            cov_file="${cov_path}/${ct_value}.txt.gz"            
+            if [[ ! -f "$db_file" ]]; then
+                echo "DB file not found: $db_file" >&2
+                continue
+            fi
+            if [[ ! -f "$cov_file" ]]; then
+                echo "Covariance file not found: $cov_file" >&2
+                continue
+            fi
+            echo "Processing ${disease_name} - ${tissue} - ${ct_value}"
+            /public/home/liuxy/MetaXcan-master/software/SPrediXcan.py \
+                --model_db_path "$db_file" \
+                --covariance "$cov_file" \
+                --keep_non_rsid \
+                --model_db_snp_key VarID \
+                --gwas_file "$gwas_files" \
+                --snp_column VariantID \
+                --effect_allele_column effect_allele \
+                --non_effect_allele_column other_allele \
+                --zscore_column zscore \
+                --beta_column beta \
+                --pvalue_column P.value \
+                --output_file "$output_file" > "$log_file" 2>&1
+        done
+    done
+done 
